### ISSUE TITLE
CancellationToken support

### ISSUE THREAD

**Issue by nesterenko-kv** [Azure/azure-notificationhubs-dotnet#101]
As far as I can see, `CancellationToken` can be used to cancel http calls, but it is simply removed in public overloads. What are the reasons for this? I am ready to do PR to bring it out.

**Comment by marstr** [comment]
Howdy @nesterenko-kv,

We'd accept this contribution. It's something on our backlog that's just never bubbled to the top.

Do keep in mind, we want/need to maintain both source and binary compatibility with these changes. For that reason, adding a parameter (even an optional one) to an existing method is a non-starter. However, adding a new overload that accepts a `CancellationToken` for each method would work well.
