### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by pzbyszynski** [Azure/azure-notificationhubs-dotnet#102]
Hi,

for the last few days I am constantly getting `System.ArgumentException` exception

```
The Apns certificate is expired. .TrackingId:66d9de0f-7f70-4451-b7a8-344003a45da5_G6,TimeStamp:11/26/2019 8:52:24 AM The Apns certificate is expired. 
```

I double-checked on iTunes Connect and the certificates that are uploaded to Azure are valid (will expire in few months)

Any help on that would be appreciated

**Comment by marstr** [comment]
Howdy @pzbyszynski,

Any chance the certificate has been revoked, or you've got a mismatch between "Sandbox" and "Production"?

**Comment by pzbyszynski** [comment]
@marstr I have regenerated certificate on iTunes Connect and uploaded it to Azure to, and still have the same exception:

```
The Apns certificate is expired. .TrackingId:7e74164a-b674-41a7-a48a-d7a86d510910_G22,TimeStamp:11/27/2019 3:50:24 
```


Also,  push notifications worked for a long time, and few days ago started to throw exceptions for several notification hubs :/

**Comment by marstr** [comment]
Sorry to hear it, @pzbyszynski. Mind filing a support ticket through the Azure portal? You may have to work through some triage steps, but if it's a server side problem it'll escalate to someone on my team. That way we'll have more secure channels for communicating about your account specifics.

Thanks!

**Comment by pzbyszynski** [comment]
@marstr I have submitted a ticket (119120423002123) using my Cloud Solution Provider
