### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by dluc** [Azure/azure-notificationhubs-dotnet#108]
The example at https://github.com/Azure/azure-notificationhubs-dotnet/blob/master/Samples/SendPushSample/SendPushSample/Program.cs doesn't work.

The code is based on SDK 3, but the project imports 2.x

The example fails with:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Program.cs:line 131
```

> outcomeDetails = await nhClient.GetNotificationOutcomeDetailsAsync(notificationId);

Because `notificationId` is null.

After debugging the SDK I noticed that the code is looking for a `Location` header, but inspecting the HTTP response from Azure notification hub, there is no such header.

Request made by the SDK:

![image](https://user-images.githubusercontent.com/371009/70747203-51dc5b00-1cdc-11ea-82f4-924668b6a727.png)

Response received by the SDK:

![image](https://user-images.githubusercontent.com/371009/70747395-c1524a80-1cdc-11ea-90e5-5c97c76dc082.png)

Any suggestion?

**Comment by brannon** [comment]
Thanks for pointing this out. We will update the import to reference 3.x.

As for the notification ID, that value (and the notification outcome) is only valid for the Standard SKU. Free and Basic don't provide telemetry and the Notification ID is not returned.

We should update the sample to handle the different SKUs better.

**Comment by mpodwysocki** [comment]
Sample updated to use only Standard SKU for the check for Location Header/Notification ID.
