### ISSUE TITLE
NotificationHub - server-side interference with APNS headers breaks VOIP notifications

### ISSUE THREAD

**Issue by sadgit** [Azure/azure-notificationhubs-dotnet#114]
Notification Hubs now try (and fail) to infer the value for `apns-push-type`

No account is taken of `voip` bundle ids

There is also no facility in the Test Send facility to specify the `apns-push-type` for the test message.

This specifically breaks the debugging of VOIP notifications.

**Comment by mpodwysocki** [comment]
Closed as per issue is fixed on the backend
