### ISSUE TITLE
Microsoft.Azure.NotificationHubs version 3.3.0 APNs: Token Authentication Mode not working

### ISSUE THREAD

**Issue by timnot90** [Azure/azure-notificationhubs-dotnet#115]
Hi,

I am trying to switch from authentication mode "Certificate" to "Token". According to the [documentation](https://docs.microsoft.com/bs-cyrl-ba/azure/////notification-hubs/notification-hubs-push-notification-http2-token-authentification) it should be enough to change the credentials in the azure portal. 

After doing that, the "Test Send" of the portal still works as expected: the push notifications arrive on the devices. 

But when using the Microsoft.Azure.NotificationHubs SDK, nothing is sent to the client. 

When I set the "enableTestSend" flag while creating the NotificationHub Client (NotificationHubClient.CreateClientFromConnectionString("<connectionString>", "<hubName>", true)), and look at the result of the SendNotificationAsync method, I get a failure for each registered apple device, saying "The Token obtained from the Token Provider is wrong".

Here is my notification body:

```
{
   "data":{
      "someAdditonalData":"data"
   },
   "aps":{
      "alert":"Notification Text"
   }
}
```

I set the following headers:

- apns-priority: 5
- apns-topic: my.bundle.id
- apns-collapse-id: 10

Further, the SDK seems to add another header: "ServiceBusNotification-Format: apple"

I don't see what I am missing here. Shouldn't my code be the same, no matter what authentication mode I use?

Thanks in advance.

Best regards

**Comment by brannon** [comment]
Hi @timnot90, moving from certificate-based auth to token-based auth should "just work". We would need more information in order to investigate your issue. Can you create a support request in the Azure Portal for this? When viewing your Hub resource, you can click "New support request" in the left menu. That will route to the service team.

Thanks!

**Comment by timnot90** [comment]
Since we're currently not production ready with our product, we don't have a subscription plan which allows us to ask for technical support.

But I don't think that the problem is on our side, because:

- When using certificate-based authentication, our coding works as expected. => Our coding cannot cause the problem. 
- After switching to token-based authentication, the "Test Send" on the Azure portal still works. => The APNs, our Notification Hub instance and the client devices should be configured correctly. 
- I was even able to send a notification manually using the REST API.

Therefore it appears to me that the only party left is the Notification Hub SDK.

**Comment by timnot90** [comment]
After some more debugging, I now finally managed to get it running.

It seems that the "apns-topic" header breaks the request. As soon as I remove it, the request passes.

Which is interesting, because when we send the request directly to APNs with the following curl command, it's working.

`curl --verbose \
   --header "content-type: application/json" \
   --header "authorization: bearer $jwt" \
   --header "apns-topic: $bundleId" \
   --data "$payload" \
   $endpoint/3/device/$deviceToken`

In the documentation of Notification Hub I cannot find any hint that there should be some special treatment for this header. 

Do you have any idea why you cannot set the header and what you can do instead? I cannot find any property on an AppleNotification or something similar.

**Comment by timnot90** [comment]
Just stumbled over the following stackoverflow question: https://stackoverflow.com/a/44115101

It seems that Notification Hub internally sets the apns-topic header according to the configuration you make on the portal.

I guess the documentation for token-based authentication should include this little detail. :-)
