### ISSUE TITLE
Sending data and notification property to FCM

### ISSUE THREAD

**Issue by junelau** [Azure/azure-notificationhubs-dotnet#116]
We are currently using `CreateRegistrationAsync` works to send a payload that ends up the `data` property when received by an Android device.  Which works fine when the app is in the foreground, but doesn't result in a push notification when the app is in background or stopped.

However, we need the payload to be:
```json
{
  "data" :  { 
      "objectId" : 4,
      "name" : "Joe Smith"
  },
  "notification" : { 
      "title" : "This is a title",
      "body" : "And this is a body"
}
```

This is to match the specification from Firebase:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

How can I register a template to include both "data" and "notification" keys please? I have tried just adding "notification" in my template, but it ends up being nested under "data" - rather than being a sibling. 

TIA 😃

**Comment by omora** [comment]
Have you tried:
` var fcmInstallation = new Installation
            {
                InstallationId = InstallationId,
                Platform = notificationPlatform,
                PushChannel = deviceHandle,
                PushChannelExpired = false,
                Tags = new[] { "fcm" }
            }; 
fcmInstallation.Templates.Add("template3", new InstallationTemplate
            {
                Body = JsonConvert.SerializeObject(new
                {
                    priority = "high",
                    data = new { title = "Reale-PRE", body = "$(shortText)" },
                    notification = new { title = "Reale-PRE", body = "$(shortText)" }
                })
            });

            await hub.CreateOrUpdateInstallationAsync(fcmInstallation);`

**Comment by junelau** [comment]
thanks @omora 
Together with #10 that solved my problem 😄
