### ISSUE TITLE
Updating from 3.2.1 to 3.3.0 breaks RegisteredForRemoteNotifications()

### ISSUE THREAD

**Issue by IeuanWalker** [Azure/azure-notificationhubs-dotnet#126]
Im using xamarin.forms and when i upgraded the Microsoft.Azure.NotificationHubs from 3.2.1 to 3.3 the `RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)` stopped being called.

**Comment by mpodwysocki** [comment]
Closing as per stale issue.  Please reopen in the [azure-notificationhubs-xamarin](https://github.com/Azure/azure-notificationhubs-xamarin) repository if this is still an issue.
