### ISSUE TITLE
Import Microsoft.Azure.NotificationHubs fails

### ISSUE THREAD

**Issue by markbeij** [Azure/azure-notificationhubs-dotnet#130]
Following the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies) I want to import Microsoft.Azure.NotificationHubs.

```
#r "Newtonsoft.Json"
#r "Microsoft.Azure.NotificationHubs"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
}
```

Testing this function I get a 500 response. The logging says:
_2020-06-18T10:29:56Z   [Error]   run.csx(2,1): error CS0006: Metadata file 'Microsoft.Azure.NotificationHubs' could not be found_

I created this in a shiny new Function App .Net Core 3.1

**Comment by mpodwysocki** [comment]
@markbeij confirmed this is a bug and we will get to this as soon as we can.

**Comment by mpodwysocki** [comment]
Linking https://github.com/Azure/azure-functions-host/issues/6773 as an issue here

**Comment by mpodwysocki** [comment]
Closing as per not supported anymore.
