### ISSUE TITLE
Include in documentation how to achieve same results with functionality that doesn't exist any longer in Microsoft.Azure.NotificationHubs versions to 3.0.0+

### ISSUE THREAD

**Issue by gmndrg** [Azure/azure-notificationhubs-dotnet#134]
Several developers when migrating from old Microsoft.Azure.NotificationHubs versions to 3.0.0+ have issues when trying to migrate code and understanding that Hub management functionality has been removed from the data plane SDK (Microsoft.Azure.NotificationHubs) and is now available via ARM SDK (Microsoft.Azure.Management.NotificationHubs or Microsoft.Azure.Management.NotificationHubs.Fluent).

Please include samples in public documentation of how to use the management SDKs when migrating from old SDK versions to 3.0.0+ to perform the same operations as of the functionality stated here: https://azure.microsoft.com/en-us/blog/push-notification-hub-telemetry-expiry-update/

Thank you!

**Comment by stankovski** [comment]
Management functionality was ported back into this SDK and is currently available in `4.0.0-preview` version - https://www.nuget.org/packages/Microsoft.Azure.NotificationHubs/4.0.0-preview2

**Comment by mpodwysocki** [comment]
Closing as per releasing of the 4.0 SDK
