### ISSUE TITLE
ASP.NET Core 2.1 support

### ISSUE THREAD

**Issue by noxi515** [Azure/azure-notificationhubs-dotnet#167]
I cannot use this library inside ASP.NET Core 2.1 apps (depends on Microsoft.Extensions.* 2.1.x).
Please tell me why you use the latest Microsoft.Extensions libs.

**Comment by mpodwysocki** [comment]
@noxi515 as noted in our README, we support a minimum of .NET Core 3.1

**Comment by noxi515** [comment]
I read that.
Is the minimum supported version a common policy for "Microsoft.Azure.*" libraries?
