### ISSUE TITLE
Microsoft.Azure.NotificationHubs - APNs provider API deadline

### ISSUE THREAD

**Issue by donaldashworth** [Azure/azure-notificationhubs-dotnet#186]
**Query/Question**
[Per Apple] - On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate (AAACertificateServices 5/12/2020) which replaces the old GeoTrust Global CA root certificate. To ensure a seamless transition and to avoid push notification delivery failures, verify that both the old and new root certificates for the HTTP/2 interface are included in the Trust Store of each of your notification servers before March 29. 

REF  - https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/

[Also per Apple] - October 9, 2020 The HTTP/2-based Apple Push Notification service (APNs) provider API lets you take advantage of great features, such as authentication with a JSON Web Token, improved error messaging, and per-notification feedback. If you send push notifications with the legacy binary protocol, we strongly recommend upgrading to the APNs provider API.
To give you additional time to prepare, the deadline to upgrade to the APNs provider API has been extended to March 31, 2021. APNs will no longer support the legacy binary protocol after this date.

REF - https://developer.apple.com/news/?id=c88acm2b

We are using **Microsoft.Azure.NotificationHubs.dll** (version 4.1.0.0) to submit Push Notification requests via Azure to APNs as well as GMC/FMC.  We would like to know if Microsoft.Azure.NotificationHubs.dll will require an update to satisfy either of the two upcomming events.

If action will be required on our part we would like to know what that/those actions will be.

***Why is this not a Bug or a feature Request?***
We are using Microsoft.Azure.NotificationHubs.dll and the two Apple communications suggests some form of activity/upgrade make be required in the very near future.  We do not maintain Microsoft.Azure.NotificationHubs.dll we simply use this assembly.

**Setup (please complete the following information if applicable):**
Windows 10
Visual Studio 2019 Professional
Microsoft.Azure.NotificationHubs.dll 4.1.0.0
 
 **Information Checklist**
None

**Comment by marstr** [comment]
Thanks for using Azure Notification Hubs.

We are aware of Apple's deprecation of the legacy binary protocol, and there is no action necessary for our customers.

**Comment by donaldashworth** [comment]
Thanks Martin.

Is the same true for the trusted root certificate depreciation occurring March 29th, 2021 (from GeoTrust Global CA root certificate to AAA Certificate Services root certificate)?

I would imagine at some point we would simply update Microsoft.Azure.NotificationHubs.dll.

Establish a Trusted Connection to APNs
Communication between your provider server and APNs must take place over a secure connection. Creating that connection requires installing the GeoTrust Global CA root certificate<https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem> (until March 29, 2021) and the AAA Certificate Services root certificate<https://comodoca.my.salesforce.com/sfc/dist/version/download/?oid=00D1N000002Ljih&ids=0683l00000G9fLm&d=%2Fa%2F3l000000VbG0%2Fh70Hv.GWfGuD79pR_if0MtGjJFcUj.NRZS_RLqEyC_4&asPdf=false> (starting March 29, 2021) on each of your provider servers.


REF - https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server

**Comment by marstr** [comment]
Correct @donaldashworth,

Both of these issues are related to the way servers must connect to Apple. We have taken the appropriate action to make sure that neither factor will require customer intervention.

**Comment by donaldashworth** [comment]
That is great to hear :o)

Thank you very much kind Sir!
