### ISSUE TITLE
[BUG] Sample does not match documentation anymore

### ISSUE THREAD

**Issue by DrMozze** [Azure/azure-notificationhubs-dotnet#188]
**Describe the bug**
This git (Xamarin/GetStartedXamarinAndroid) is mentionned in this documentation : https://docs.microsoft.com/fr-fr/azure/notification-hubs/xamarin-notification-hubs-push-notifications-android-gcm but the source code does not match with the steps described in the documentation.

**Expected behavior**
Update the git with the correct source code.

**Comment by mpodwysocki** [comment]
This is the wrong repository for this as this is a Xamarin specific issue.  The repository for the [Azure Messaging](https://github.com/xamarin/XamarinComponents/tree/main/XPlat/AzureMessaging) is where the source code lives from there.
