### ISSUE TITLE
[QUERY] Migrating from v1.0.9 to v4.1.0

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/azure-notificationhubs-dotnet#199]
I am trying to update Microsoft.Azure.NotificationHubs from 1.0.9 to 4.1.0 in ServiceBusExplorer, https://github.com/paolosalvatori/ServiceBusExplorer/issues/472#issuecomment-860186523. 

The problem is the following properties in the NotificationHubDescription class which do not exist in the latest version of Microsoft.Azure.NotificationHubs. How should they be handled?

- DailyMaxActiveDevices
- DailyMaxActiveRegistrations
- DailyOperations
- UserMetadata

**Comment by mpodwysocki** [comment]
@ErikMogensen Yes, this is a regression from the 1.0.9 release as we reintroduced the management plane operations. Will do some research as to what effort it may take to add it back.

**Comment by ErikMogensen** [comment]
Thanks @mpodwysocki. Have you had the time to look into this?

**Comment by mpodwysocki** [comment]
@ErikMogensen We have it in our internal backlog and will try to get to it as soon as we can, given that we have limited cycles.

**Comment by ErikMogensen** [comment]
Does it require service side changes? If only client changes are needed I might be able to create a PR for this.

**Comment by ErikMogensen** [comment]
Any news on this?

**Comment by mpodwysocki** [comment]
@ErikMogensen re-implemented in 4.1.1

**Comment by ErikMogensen** [comment]
Wonderful! @mpodwysocki, is it on its way to [nuget.org](https://www.nuget.org/packages/Microsoft.Azure.NotificationHubs/)?

**Comment by mpodwysocki** [comment]
@ErikMogensen Yes, we are working on getting a NuGet package out as soon as we can.  We have had some publishing issues which should be resolved soon.

**Comment by mpodwysocki** [comment]
@ErikMogensen I am no longer on the Azure Notification Hubs team.  ping @marstr and @aimankhan

**Comment by ErikMogensen** [comment]
@marstr and @aimankhan, has anyone of you looked into the issues of publishing the NuGet package for 4.1.1?
