### ISSUE TITLE
Az login not working in powershell but its working in cmd[BUG]

### ISSUE THREAD

**Issue by gyalamanch** [Azure/azure-notificationhubs-dotnet#201]
PS C:\Users\gyalamanch001> get-command az.bat
get-command : The term 'az.bat' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ get-command az.bat
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (az.bat:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 

this is the error i am getting

**Comment by mpodwysocki** [comment]
This is the repository for Azure Notification Hubs.  I believe you are looking for the [Azure CLI](https://github.com/Azure/azure-cli) which has the az command.
