### ISSUE TITLE
How to get the list of NotificationHubs from the connectionstring?

### ISSUE THREAD

**Issue by thtrunck** [Azure/azure-notificationhubs-dotnet#22]
In the old package (before the .net standard) we use to be able to do something like:
```
var namespacemanager = NamespaceManager.CreateFromConnectionString(connectionString);
namespacemanager.GetNotificationHubs();
```

I guess those "management" api were remove to the package and put into Microsoft.Azure.Management.NotificationHub. My problem with that package is that I don't see how to simply use the connectionstring.

It's kind of the same story as the one in servicebus here: https://github.com/Azure/azure-service-bus-dotnet/issues/358.
But they finally decided to add back some management capabilities in Microsoft.Azure.ServiceBus using directly the connectionstring

So I guess my question is how could I get the list of NotificationHubs from the namespace connectionstring and if it's not possible yet, is there any plan/timeline to add that back to the .net standard package.

Thanks

**Comment by brannon** [comment]
As you found, that functionality was moved to the Azure "management" SDK.

At this time there are no plans to re-add the management capabilities to this SDK.

I'm going to close this issue, but feel free to leave feedback.

**Comment by thtrunck** [comment]
The problem is not that it was moved, it's that with the Azure "management" SDK is that there is no way to just use the notification connectionString.
Really it's the same impact as for ServiceBus and this discussion can be relevant: https://github.com/Azure/azure-service-bus-dotnet/issues/65

In our case we only have the connection string and the management library doesn't connect using connection string. So it's a blocker to migrate to Dotnet Core.
