### ISSUE TITLE
[QUERY] How to send Notification to Installations Across Platforms for a UserId 

### ISSUE THREAD

**Issue by nicholascm** [Azure/azure-notificationhubs-dotnet#223]
**Query/Question**
The examples here for using `Installation` seem to assume that you always know the platform of the UserId before you send the notification. 
https://github.com/Azure/azure-notificationhubs-dotnet#send-to-a-user-id

Is there a way to send to a UserId tag across all platforms? The only way I have been able to find is to call both the `hub.SendAppleNativeNotificationAsync(alert,  $"$UserId:{{{userId}}}")` and `hub.SendFcmNativeNotificationAsync(payload,  $"$UserId:{{{userId}}}")` every time. 

Background:
My current approach is to open an API for user's to register their device(s) via the backend using the recommended Installation method (and adding the UserId) and then when I want to notify that user, I am trying to find the most efficient way. 

***Why is this not a Bug or a feature Request?***
It seems like this would be supported as we provide the platform information during the creation of the Installation. 

**Setup (please complete the following information if applicable):**
 - OS: Mac OS Big Sur
- iDE: VSCode
 - Version of the Library used: v4.1.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by marstr** [comment]
Thanks for your query. We have [some documentation](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-templates-cross-platform-push-messages) and a blog post that you can [read here](https://devblogs.microsoft.com/azure-notification-hubs/use-templates-effectively/) which describe how you can add templates to your installations to solve this problem.

In broad strokes, what it comes down to is you can save payloads as part the Installation and execute a "template send" with a tag expression to target both iOS and Android devices with a single send operation. You can parameterize templates, so you can inject values at send-time.

Also, while we don't have any definitive plans at time of writing, in future api-versions I could imagine adding a [multipart](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) send operation that could target multiple platforms at once.
