### ISSUE TITLE
Microsoft.Azure.NotificationHubs.GcmRegistrationDescription; Microsoft.Azure.NotificationHubs.NamespaceManager ; Microsoft.Azure.NotificationHubs.NotificationHubDescription classes are missing in  Microsoft.Azure.NotificationHubs 3.0.0 dll

### ISSUE THREAD

**Issue by Jimhox** [Azure/azure-notificationhubs-dotnet#24]
We tried to upgrade to  Microsoft.Azure.NotificationHubs 3.0.0  from 1.0.6 but our build is failing,  I see Microsoft.Azure.NotificationHubs.GcmRegistrationDescription; Microsoft.Azure.NotificationHubs.NamespaceManager ; .Microsoft.Azure.NotificationHubs.NotificationHubDescription classes are missing in  Microsoft.Azure.NotificationHubs 3.00 dll

**Comment by igprya** [comment]
Starting version 3.0.0, all Gcm* types are marked as obsolete and no longer supported by the SDK due to Google [deprecating GCM platform on April 10, 2018](https://developers.google.com/cloud-messaging/faq). Please consider using Fcm* types (for example, FcmRegistrationDescription) in your code, they are identical to their Gcm counterparts and support newer FCM platform.

Unfortunately at the moment I'm unable to comment with any certainty on other errors you're experiencing. It seems that those classes were removed at some point as they aren't present in the earliest version available in the repository (2.0.1).

**Comment by brannon** [comment]
@Jimhox this repository only contains the 2.0.0 and future releases. The previous versions were based on another codebase that isn't open source.

In the 2.0.0 release, some functionality was moved to the Azure SDK for .NET (specifically https://github.com/Azure/azure-sdk-for-net/tree/master/src/SDKs/NotificationHubs). Namespace and Hub management APIs can be found there.

Regarding `GcmRegistrationDescription`, Google is deprecating GCM (in favor of FCM) and the 3.0.0 release no longer includes those models. The `FcmRegistrationDescription` model should be a drop in replacement.

**Comment by brannon** [comment]
I'm going to close this bug, since the changes are intentional. Feel free to follow up with additional questions.

**Comment by Jimhox** [comment]
Thank you for help on the issue

**Comment by Jimhox** [comment]
NotificationHubDescription and  NamespaceManager are missing in  https://github.com/Azure/azure-sdk-for-net/tree/master/src/SDKs/NotificationHubs

**Comment by Jimhox** [comment]
These two classes:
![image](https://user-images.githubusercontent.com/22205504/52373928-cab1bd00-2a10-11e9-8935-9dc5d6496ea9.png)

**Comment by brannon** [comment]
`NotificationHubDescription` is replaced by `NotificationHubResource` (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.notificationhubs.models.notificationhubresource?view=azure-dotnet).

To get one, you would use the `INotificationHubsOperations.GetAsync()` extension method (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.notificationhubs.notificationhubsoperationsextensions.getasync?view=azure-dotnet#Microsoft_Azure_Management_NotificationHubs_NotificationHubsOperationsExtensions_GetAsync_Microsoft_Azure_Management_NotificationHubs_INotificationHubsOperations_System_String_System_String_System_String_System_Threading_CancellationToken_)

Something like:

```c#
var client = new NotificationHubsManagementClient(credentials);
var notificationHub = await client.NotificationHubs.GetAsync(resourceGroupName, namespaceName, hubName);
```
You must supply the right credentials based on your user or service principal in Azure. See the following `NotificationHubsManagementClient` constructor:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.notificationhubs.notificationhubsmanagementclient.-ctor?view=azure-dotnet#Microsoft_Azure_Management_NotificationHubs_NotificationHubsManagementClient__ctor_Microsoft_Rest_ServiceClientCredentials_System_Net_Http_DelegatingHandler___

**Comment by chistov** [comment]
@brannon , I'm trying to write client code with your example and it fails. I mean:

`var client = new NotificationHubsManagementClient(credentials);
var notificationHub = await client.NotificationHubs.GetAsync(resourceGroupName, namespaceName, hubName);`

Do you know how to fix it or there to find good example?
