### ISSUE TITLE
Invalid Apns token Exception

### ISSUE THREAD

**Issue by muhammetsahin** [Azure/azure-notificationhubs-dotnet#28]
Hi,

I wrote this code and run successfuly with FCM But same code didnt work Apns I've got this error.

Any idea?

bla bla bla...

`  var installation = new Installation()
                {
                    Platform = platform,
                    PushChannel = appInstallation.PushChannel,
                    PushChannelExpired = false,
                    InstallationId = appInstallation.InstallationId, //Sample: e26741c15c284174a3566c52323a8edd
                    Tags = tags,
                    Templates = templates

                };
                await _hub.CreateOrUpdateInstallationAsync(installation);`

![image](https://user-images.githubusercontent.com/2045788/52617829-21564580-2eae-11e9-8ae6-7d4d46da3b5e.png)

Thank you.

**Comment by alex-zyl** [comment]
Hi @muhammetsahin 
PushChannel should be valid device token received from Apns and should look something like this:
```gab52f96713de22619d6a123a37238a8fa5f9ecc8dd4efc6af86d4e9ff45d92b```

**Comment by brannon** [comment]
@alex-zyl thanks for helping out! I'll go ahead and close this issue since it sounds like it was resolved.
