### ISSUE TITLE
Can I continue using the old v2 SDK after April 2019?

### ISSUE THREAD

**Issue by naxxxel** [Azure/azure-notificationhubs-dotnet#29]
There is a lot of information floating around regarding the impending deprecation of GCM in favor of FCM. What does this mean for NotificationHubs .NET SDK users? We are creating/updating registrations and are sending push notifications. Do we need to switch our backend code to V3 before April 2019? Or is this handled by Azure for us?

"If you have projects that are still using the GCM APIs, you will need to update your client and server code to use FCM before April 11, 2019. But rest assured, your existing GCM tokens will continue to work with FCM so you won't lose the ability to send messages to your existing users." (https://firebase.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html)

**Comment by brannon** [comment]
@naxxxel You're right, there is a lot of information to understand regarding the migration to FCM.

Google has stated that GCM tokens will continue to work and their FCM API supports both FCM tokens and GCM tokens.

The Notification Hubs service has already been updated to use the FCM API. Any existing devices you have registered (using a GCM token) should continue to work.

At some point, I would recommend updating your apps to use FCM and upgrade to the latest .NET SDK so you can register devices using the FCM registration classes. We do plan to remove the GCM registration classes from a future version of the SDK. But there is no requirement to update before April 2019.
