### ISSUE TITLE
[BUG] Provide new nuget packages, and docs with examples that will show how to use Azure Notification Hubs with MAUI

### ISSUE THREAD

**Issue by DeveloperLookBook** [Azure/azure-notificationhubs-dotnet#315]
**Describe the bug**
For now, your docs contain instructions for Xamarin.Form, Xamarin.Android and Xamarin.iOS, so we need new docs and new examples and probably new nuget packages that will support MAUI.

**Comment by developer9969** [comment]
Interested in this too is there any real chance of getting them. I would honestly be very very surprised if we get a reply from MS

**Comment by lomagdal2** [comment]
We don't support MAUI at this time.

**Comment by developer9969** [comment]
@lomagdal2 what does "we dont support Maui at this time" means ??  what stops using a connectionstring?

**Comment by jfversluis** [comment]
Just to clarify here, you can absolutely use Azure Notification Hubs (ANH) with .NET MAUI. What is meant here is that this library does not anything specific to support .NET MAUI at this time. We are working on content that shows how to use ANH together with .NET MAUI and there are also great community libraries out there like [Shiny](https://shinylib.net/client/push/providers/#azure-notification-hubs), that use AHN to implement push notifications.

**Comment by DeveloperLookBook** [comment]
@jfversluis Hello, Gerald! 
I apologize, but the last time I tried to use Azure Notification Hubs (ANH) with .NET MAUI, it took me two weeks to complete the integration/migration. I only succeeded because someone provided an example. Every developer I know would say that using ANH with MAUI without clear instructions is quite challenging. Additionally, we did not want to use third-party packages like Shine. This is why we are requesting updated, clear, step-by-step instructions.

**Comment by jfversluis** [comment]
No need to apologize!

I totally understand that doing this for the first time might be a chore. For the record: I work on the .NET MAUI team, not the team that maintains this library. I just wanted to clarify that it is possible to use this with MAUI. From the MAUI side of things we will be providing a sample with content and instructions soon that we can hopefully make this easier for people.

**Comment by TedMobile** [comment]
@jfversluis  Thanks for the clarification, it's a relief , we have successfully implemented push notification for iOS and android in Maui using Azure notification hub and works really well. It was a utter nightmare as many of the docs out there are outdated and permission in android are changing all the time. We have all working in our internal library and going live soon , but clients ask what provider do you use? Your response goes a long way to reassure them, as a client found exactly this thread and send us an email for clarification.Thanks again.

**Comment by baaaaif** [comment]
@TedMobile Have you managed to implement a NotificationServiceExtension?
And do push notifications arrive when the app is closed?
Unfortunately, I haven't managed to get the DidReceiveNotificationRequest call in the extension yet

So I can hardly wait for better documentation

**Comment by baaaaif** [comment]
That probably means you don't have to change the notification content and therefore don't set mutable-content to 1, right?

That's why push works with a closed app without NotificationServiceExtension

@jfversluis  it would be cool if you would also consider the mutable-content and NotificationServiceExtension case. That's where the challenge lies :)
