### ISSUE TITLE
[BUG] Notifications Sent to All Devices Instead of Targeted Device with FcmV1 Installation in Azure Notification Hubs 4.2.0

### ISSUE THREAD

**Issue by korompaidani** [Azure/azure-notificationhubs-dotnet#318]
**Describe the bug**
After upgrading to "Microsoft.Azure.NotificationHubs" Version="4.2.0" and switching to FcmV1 installations, a notification sent to a single device token unexpectedly triggers notifications to all devices registered with the FcmV1 configuration. This issue does not occur with the previous library version 4.1.0 using FCM installations.

***Exception or Stack Trace***
No exceptions or stack traces are generated, as the notifications are sent and received but with incorrect distribution.

**To Reproduce**

1. Register three device tokens using FcmV1 configuration.
`var nhClient = NotificationHubClient.CreateClientFromConnectionString(_connectionString, _hubName);
var installation = new FcmV1Installation(installationId, deviceToken);     
await nhClient.CreateOrUpdateInstallationAsync(installation);
`

2. Send a notification targeting one specific device token.
`var jsonBody = $"{{\"message\": {{\"token\": \"{deviceToken}\", \"notification\": {{\"title\":\"{title}\",\"body\":\"{body}\"}}}}}}";          
var notification = new FcmV1Notification(jsonBody);
NotificationOutcome outcome = await nhClient.SendNotificationAsync(notification);
`
Observe that all devices receive the notification instead of just the one targeted.

***Code Snippet***
See the steps above for code snippets involved in reproducing the issue.

**Expected behavior**
Notifications should be received only by the device corresponding to the targeted device token. Each device should independently receive notifications as per their specific registrations without affecting others.

**Setup (please complete the following information):**
 - Version of the Library used: 4.2.0

**Additional context**
- Removing and re-registering devices does not resolve the issue. The erroneous behavior persists where all devices receive notifications intended for a single device.
`await nhClient.DeleteInstallationAsync(installationId);
// and the devicetoken as well:
await nhClient.DeleteRegistrationsByChannelAsync(deviceToken);
// and register again
var installation = new FcmV1Installation(installationId, deviceToken);     
await nhClient.CreateOrUpdateInstallationAsync(installation);
`
- Verification of registrations confirms that each device token is correctly associated with only one installation ID. Checked by this call:
`var allRegistrations = await hub.GetAllRegistrationsAsync(0);`

**Comment by marstr** [comment]
The `SendNotificationAsync` method calls a method like the one documented here, [Send a Google Clould Message (GCM) native notification](https://learn.microsoft.com/en-us/rest/api/notificationhubs/send-gcm-native-notification), but in this case it would instead use the `ServiceBusNotification-Format` header set to `fcmv1`.

These send APIs are used in tandem with any of the registrations/installations you have used to store device records with your hub. They will query all records, and send FCM a request for each one found. You can scope the request using tag expressions to narrow the audience, all the way to down to a single device if you choose.

Here are some other resources that you may find helpful:
- [Routing and tag expressions](https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-tags-segment-push-message)
- [Registration management](https://learn.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management?source=recommendations)
- [Tutorial: Send notifications to specific devices using Notification Hubs and Google Firebase Cloud Messaging](https://learn.microsoft.com/en-us/azure/notification-hubs/push-notifications-android-specific-devices-firebase-cloud-messaging)
