### ISSUE TITLE
[QUERY] Is this project abandoned?

### ISSUE THREAD

**Issue by timvandesteeg** [Azure/azure-notificationhubs-dotnet#323]
**Query/Question**
Looking at all the latest issues, I don't see any reply from any maintainer. I know this is open-source and maintainers have a lot of things on their plate, but since this is basicly a Microsoft project I would like an update on the state of this project.

Is nobody allocated to this project? Is the regular maintainer fired? 
We are all human, so I don't want to be negative, but it would be nice if we could get an update :)

**Comment by developer9969** [comment]
Wondering the same is this project still alive?

Anyone care to respond?

**Comment by lomagdal2** [comment]
no, it's not abandoned. while i can't disclose much, i can promise that we're doing the best we can with what we've got ;)
