### ISSUE TITLE
RegistrationExistsAsync throws MessagingEntityNotFoundException if it can't find registration

### ISSUE THREAD

**Issue by JakubHolovsky** [Azure/azure-notificationhubs-dotnet#38]
Consider following code:

```
var exists = await _hub.RegistrationExistsAsync(registrationId);
                if (exists)
                    await _hub.DeleteRegistrationAsync(registrationId);
```
I am making sure the registration exists before I try to delete it - simply to avoid MessagingEntityNotFoundException.

However RegistrationExistsAsync throws "MessagingEntityNotFoundException" - I do not see the point in that. Shouldn't it return "false" if it can't find the registration?

**Comment by brannon** [comment]
@JakubHolovsky yeah, that is definitely unintended behavior! I'll get this on our backlog to fix. We also accept pull requests 😉 .

**Comment by JakubHolovsky** [comment]
we have fixed the issue, closing
