### ISSUE TITLE
SendTemplateNotificationAsync - removing invalid registration

### ISSUE THREAD

**Issue by JakubHolovsky** [Azure/azure-notificationhubs-dotnet#39]
This issue happens in my integration tests. Note that I am running these tests from my local machine. However they were passing when I was on version 1.x of the nuget package. Since 2.x this has started happening.

(for simplicity I list here only the main methods - do consider that the registration id i pass in there is always the correct one)

I call:
1. CreateOrUpdateRegistrationAsync
2. DeleteRegistrationAsync
this always passes and I never get an exception

I call:
1. CreateOrUpdateRegistrationAsync
2. SendTemplateNotificationAsync
3. DeleteRegistrationAsync
this never passes and I get MessagingEntityNotFoundException on DeleteRegistrationAsync.

Does SendTemplateNotificationAsync method somehow deletes the invalid registration that is created in CreateOrUpdateRegistrationAsync. 
In my theory - it can'f find a device then it removes the registration automatically - but I do not know. Can you please verify this?

**Comment by marstr** [comment]
I can confirm that this is the expected behavior! When the server detects an invalid registration, it goes ahead and cleans it up to prevent further processing.
