### ISSUE TITLE
Migrating from GCM to FCM

### ISSUE THREAD

**Issue by JasonKraft** [Azure/azure-notificationhubs-dotnet#43]
I've upgraded my nuget package from 1.0.9 to 3.0.2 to migrate from GCM to FCM. Based on the release description, it looks like GCM methods now route through the FCM api. So is there anything in my code I need to change (e.g. can I continue to use SendGcmNativeNotification)?

**Comment by brannon** [comment]
@JasonKraft Sorry for the confusion (and slow response!). Our migration from GCM to FCM was not as clean as it should have been.

For now, the Gcm and Fcm methods in the SDK should be interchangeable. We are supporting the FCM Legacy API, which is functionally equivalent to the GCM API:
https://firebase.google.com/docs/cloud-messaging/http-server-ref

We posted the following article to our documentation:
https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-gcm-to-fcm

Let us know if you have any more questions.
