### ISSUE TITLE
FCM registration token colon not allowed

### ISSUE THREAD

**Issue by marcobaldo** [Azure/azure-notificationhubs-dotnet#48]
I'm getting the following error when calling CreateOrUpdateInstallationAsync:

> ArgumentException:  The path sb://xxxxxxxxx.servicebus.windows.net/splashnotifdev/installations/xxxxxx:xxxxxxxxxxxxx?api-version=2017-04&" contains character(s) that are not allowed by Service Bus. Entity segments can contain only letters, numbers, periods (.), hyphens (-), and underscores (_)..TrackingId:98f12ac0-c905-4a63-a68d-c77f61cdb1ad_G5,TimeStamp:6/1/2019 3:16:11 PM

Where the installationId obtained from Firebase's onSuccessListener is a token with colon in it.
The token appears to be similar to a GCM token but prefixed with a few characters and a colon, e.g. (rest of the token masked):
`dTxbVurMB3E:APA91bFsadfjklasfhjdsajkfdhaslkfhdjklsafhjklasdhlhasklfhjkasfhdjlkasfhdasjkdhf`

Note that I am not calling this from Android, but passing the token to a .NET backend which calls the CreateOrUpdateInstallationAsync() method. I've also tried urlencoding the token or replacing : with %3a, which only leads to an Unauthorized error (despite the SAS working correctly, e.g. for Apns registrations).

> UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. Reason: 40104: Invalid authorization token audience..TrackingId:7cf7cb94-9041-486c-8ccd-72e4f1d68d40,TimeStamp:2019-06-01T15:25:41.5055837Z

**Comment by brannon** [comment]
This is by design. The token provided by FCM is not intended to be used as the installation ID. The token value can change over time, while the intention of the installation ID is to uniquely identify a particular app installation. The installation ID should be stable, while the FCM token should be specified as a property of the installation and updated frequently.

**Comment by marcobaldo** [comment]
@brannon does this mean that for fcm, we can only use registrations and not installations?

**Comment by brannon** [comment]
@marcobaldo no, it means you shouldn't use the FCM token as the installation ID. They are not the same thing. The installation ID can be any valid value. People typically use a GUID. It should be a value that you know and control.

The FCM token is not a value that you control and it contains characters that are not valid for use in the installation ID. The FCM token will change occasionally and unexpectedly.

When you create (or update) the installation you should set the [PushChannel property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.installation.pushchannel?view=azure-dotnet#Microsoft_Azure_NotificationHubs_Installation_PushChannel) to the value of the FCM token.

**Comment by marcobaldo** [comment]
@brannon that makes so much more sense.
