### ISSUE TITLE
Registration method support Baidu Cloud Push, but Installation method does not.

### ISSUE THREAD

**Issue by xyfoo** [Azure/azure-notificationhubs-dotnet#50]
Is this a bug/gap or is this a deliberate choice to exclude it?

[Documentation for supported installation platform](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationplatform?view=azure-dotnet)

**Comment by brannon** [comment]
@xyfoo thanks for the bug report. We will investigate. I believe Baidu should be supported for installations too.

**Comment by JakubHolovsky** [comment]
#75 recently there has been a commit regarding to this

**Comment by petro2050** [comment]
any update on this?

**Comment by mpodwysocki** [comment]
Closing as per resolved.
