### ISSUE TITLE
apns-collapse-id not working

### ISSUE THREAD

**Issue by arek-avanade** [Azure/azure-notificationhubs-dotnet#60]
As far as I can see, one of your SDK samples (SendPushSample) provides apns-collapse-id header to APNS. In my case however this doesn't work as expected - notifications don't 'collapse'. Has anyone tested if these headers are passed to APNS and if behavior was correct?

I'm wondering if the type of authentication is important here in Azure Notification Hubs, since I'm using old certificate-based authentication rather than new key-based authentication.

**Comment by brannon** [comment]
@arek-avanade most APNS headers are not supported when using certificate-based authentication. This is a limitation in the backend implementation.

If you can switch to using the new key-based authentication, then `apns-collapse-id` should work. The value you specify is just passed through to APNS.

Hope that helps!

**Comment by arek-avanade** [comment]
@brannon Thanks, that makes it clear. It might be worth adding this important detail to the documentation and/or generated documentation for relevant methods so that developers are aware.
