### ISSUE TITLE
'CreateClientFromConnectionString' Functionality Using "enableTestSend"

### ISSUE THREAD

**Issue by alaskanrogue** [Azure/azure-notificationhubs-dotnet#67]
I am attempting to diagnose a FCM notification to a single device with a channel scenario which isn't being delivered. I am trying to use 'CreateClientFromConnectionString' with 'enableTestSend' enabled. This the only method that I know of for this type of debugging, but when the notification is sent it crashes the Azure debugging instance and disconnects from  VS2019. This event has been consistent since enabling the parameter.

I opened a support case which was assigned to the Azure Service Bus Team, Case 119080124004303. It was recommended that I open an issue here. The recommendation is based on the following exception which the team found:

{"level":1,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":2,"method":"System.Threading.ExecutionContext.RunInternal","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":3,"method":"System.Threading.ExecutionContext.Run","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":4,"method":"System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":5,"method":"System.Threading.ThreadPoolWorkQueue.Dispatch","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0}]},{"id":65666079,"outerId":29613747,"typeName":"System.ArgumentNullException","message":"Value cannot be null.\r\nParameter name: notificationId","hasFullStack":true,"parsedStack":[{"level":0,"method":"Microsoft.Azure.NotificationHubs.NotificationHubClient+<GetNotificationOutcomeDetailsAsync>d__50.MoveNext","assembly":"Microsoft.Azure.NotificationHubs, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","line":0},{"level":1,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":2,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":3,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0},{"level":4,"method":"NotificationService.AsynchNotification+<StartNotificationTask>d__13.MoveNext","assembly":"WWW, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"C:\\Projects\\IdentityCheckpoint\\VS2019\\IdentityCheckpoint\\WWW\\NotificationHandler.cs","line":158}]}],"severityLevel":"Critical"}}}
The thread 0x6c8 has exited with code 0 (0x0).

**Comment by marstr** [comment]
Howdy @alaskanrogue,

The stack trace included above doesn't give me quite enough to get started on debugging this issue. Mind providing a representative snippet of code that results in the error your seeing?

**Comment by alaskanrogue** [comment]
Howdy back, @marstr,

Below is the class implementation. It is designed to handle notifications to basically all device types. Device type 1 is UWP, type 2 is iOS and type 3 is Android. If not enabled, UWP and iOS is delivering raw messages; Android is not, hence my enabling the parameter. I am consistently being told "Target not found". StartNotificationTask() contains the hub call.

    class AsynchNotification
    {
        protected int deviceType;
        protected string ownerUri;
        protected WindowsNotification winMessage;
        protected string notice;
        protected bool receivedResponse;
        public string finalSessionStatus;
        protected bool responseReceived;
        protected bool notificationAborted;
        protected DateTime startTime;
        protected int responseTimeSpan = 3;

        protected NotificationRequestHandler handler;

        public AsynchNotification(NotificationRequestHandler callHandler)
        {
            handler = callHandler;
        }

        public void StartNotificationWork(int type, string uri, WindowsNotification notificationToSend, string noticeToSend)
        {
            deviceType = type;
            ownerUri = uri;
            winMessage = notificationToSend;
            notice = noticeToSend;

            ThreadPool.QueueUserWorkItem(new WaitCallback(StartNotificationTask), null);
        }

        private async void StartNotificationTask(Object workItemState)
        {
            NotificationOutcome outcome;
            NotificationDetails details;

            // Set the Notification Hubs credentials for the Mobile App
            try
            {
                string notificationHubConnection = "Endpoint=sb://Xnotifications.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=53Be0m1oGSuDnbyr3aGSO+nraHGPy/id/khhvnHzdWc=";
                string notificationHubName = "XNotificationsHub";

                // To Debug, set to true;
                bool enableTestSend = true;
                NotificationHubClient hub = NotificationHubClient.CreateClientFromConnectionString(notificationHubConnection, notificationHubName, enableTestSend);

                // Send the push notification.
                try
                {
                    // UWP
                    if (deviceType == 1)
                    {
                        outcome = await hub.SendDirectNotificationAsync(winMessage, ownerUri);
                        if (outcome.NotificationId != "")
                        {
                            details = await hub.GetNotificationOutcomeDetailsAsync(outcome.NotificationId);
                            handler.notificationSent = false;
                        }
                        else
                        {
                            handler.notificationSent = true;
                        }
                    }
                    // iOS
                    else if (deviceType == 2)
                    {
                        outcome = await hub.SendAppleNativeNotificationAsync(notice, ownerUri);
                        if (outcome.NotificationId != "")
                        {
                            // Un-remark to debug
                            // Change Azure Notification Hub Pricing Tier to Standard
                            await Task.Delay(60000);
                            details = await hub.GetNotificationOutcomeDetailsAsync(outcome.NotificationId);
                            handler.notificationSent = false;
                        }
                        else
                        {
                            handler.notificationSent = true;
                        }
                    }
                    // Android
                    else if (deviceType == 3)
                    {
                        outcome = await hub.SendFcmNativeNotificationAsync(notice, ownerUri);
                        if (outcome.NotificationId != "")
                        {
                            Task t = Task.Run(() =>
                            {
                                int a = 3;
                            });

                            t.Wait(15000);

                            details = await hub.GetNotificationOutcomeDetailsAsync(outcome.NotificationId);

                            handler.notificationSent = false;
                        }
                        else
                        {
                            handler.notificationSent = true;
                        }
                    }
                }
                catch (System.Exception ex)
                {
                    finalSessionStatus = "An error occurred during query execution: " + ex;
                    responseReceived = false;
                    notificationAborted = true;

                    throw new ApplicationException("An error occurred during query execution: ", ex);
                }

                startTime = DateTime.Now;
            }
            catch (WebException ex)
            {
                if (ex.Status == WebExceptionStatus.Timeout)
                {
                    receivedResponse = false;
                    finalSessionStatus = "No request was able to be sent within the allocated time period.";
                    responseReceived = false;
                }
                else
                {
                    finalSessionStatus = "An error occurred during query execution: " + ex;
                    responseReceived = false;
                    notificationAborted = true;

                    throw new ApplicationException("An error occurred during query execution: ", ex);
                }
            }
      }
}

**Comment by alaskanrogue** [comment]
Debugging just now a different issue, but enableTestSend enabled because of having created the code snippet, I caught this exception.
![Exception](https://user-images.githubusercontent.com/14001196/62823287-a8cef980-bb5d-11e9-876d-632567e959d1.png)

**Comment by marstr** [comment]
@alaskanrogue, looks like you accidentally included a `SharedAccessKey` in the post above. Please take a moment to generate a new primary access policy for your Notification Hub, as this one has been compromised.

This gives me what I need to start investigating though, thank you!

**Comment by alaskanrogue** [comment]
Thanks. Regenerated.

**Comment by marstr** [comment]
Howdy @alaskanrogue,

Try switching the line

``` C#
 if (outcome.NotificationId != "")
```

to 

``` C#
if (string.IsNullOrWhitespace(outcome.NotificationId))
```

Unless you're using the "Standard" SKU (e.g. most expensive SKU) of Notification Hubs, we don't return a Notifcation ID. I believe that value just happens to be null instead of the empty string, and the check above is missing it and trying to call a function that requires a notification ID.

**Comment by marstr** [comment]
I'm going to close this issue out, under the assumption that this operation truly is not supported while using `enableTestSend`. However, if there's any reason to believe otherwise, I'm happy to open this issue back up.
