### ISSUE TITLE
C# SDK 2.0.0-preview2 stops working after 1 hour

### ISSUE THREAD

**Issue by kspearrin** [Azure/azure-notificationhubs-dotnet#9]
I am trying out the new 2.0.0-preview2 available on nuget in a ASP.NET Core 2.1 application on `netcoreapp2.1`. This seems to work fine as a drop in replacement for 1.0.9 without any breaking changes.

In my application, `NotificationHubClient` is initialized as a properly of a singleton instance. I notice that after ~1 hour of the application running, any `NotificationHubClient` functions that are invoked no longer work. My application does not throw any errors, but all activity to my Notification Hub ceases (confirmed by looking at metrics in the Azure portal) and I no longer get push notifications to my apps. If I restart the server (causing the singleton instance to `new` again) things again start working for ~1 hour and then stop again.

Due to the nature of the consistent 1 hour lifetime of things working, I suspect that the `NotificationHubClient` instance is not renewing it's SAS token or something that has a 1 hour lifetime. To workaround this problem I now keep track of internal 30 minute timer where I `new` the `NotificationHubClient` up again every 30 minutes. Doing this resolves the problem.

**Comment by mpodwysocki** [comment]
@kspearrin closed as per #13
