### ISSUE TITLE
CreateOrUpdateInstallationAsync would not update push channel

### ISSUE THREAD

**Issue by hajuuk** [Azure/azure-notificationhubs-dotnet#95]
I try to call CreateOrUpdateInstallationAsync in my backend service for install device, however, it would not affect correctly when the update information includes the push channel.

I use the following code to test:

            var existInstallation = await hub.GetInstallationAsync(installation.InstallationId);

            await hub.CreateOrUpdateInstallationAsync(installation);

            var updatedInstallation = await hub.GetInstallationAsync(installation.InstallationId);

            if (existInstallation.PushChannel == updatedInstallation.PushChannel && updatedInstallation.PushChannel != installation.PushChannel)
            {
                throw new Exception("Push channel update failed.");
            }

It should not throw the Exception if the push channel updated correctly.

Additionally, if I delete the installation and then install again, it can set the new push channel.

**Comment by brannon** [comment]
Installation updates are asynchronous and often times the Get/Update/Get cycle will not return the result you expect because the Update operation is processed by the server in the background.

**Comment by stefanodonofrio** [comment]
Is there any way to get any Result code when CreateOrUpdateInstallationAsync is executed then? To be honest the Update/Get cycle is what I got in mind to check if the installation is registered correctly with the Notification Hub.

**Comment by adrianknight89** [comment]
@brannon When I await `CreateOrUpdateInstallationAsync`, I expect the installation to be created if no exception is thrown. It's never being created for me. I re-tried many times with no luck. In VS Server Explorer, I don't see it there either. Do you know why?

**Comment by greendimka** [comment]
I consider dropping the whole Azure and switch to AWS because Azure team never cares about documentation or good support. Screw them.

**Comment by Tommigun1980** [comment]
@brannon So how should this be handled then?? This needs to be fixed.

**Comment by mpodwysocki** [comment]
Closing this issue as this is working as expected.  Since the installation operations are by default, asynchronous, you cannot rely on calling the `GetInstallation` to return the latest and may be stale.  The only feedback we can give the user for saving is that the update has been enqueued.

If you are having problems with creation of installations failing as per your notification hub, please open a support ticket with the Azure Notification Hubs Team via the Azure Portal.
