### ISSUE TITLE
Microsoft.Azure.NotificationHubs.Messaging.MessagingException

### ISSUE THREAD

**Issue by pzbyszynski** [Azure/azure-notificationhubs-dotnet#97]
For the last two days I get lots of `Microsoft.Azure.NotificationHubs.Messaging.MessagingException`s without any modification in my code. I have upgraded `Microsoft.Azure.NotificationHubs` to the leatest `3.2.1.0` varsion but it didn't help. Never had this kind of exceptions before

Here is a detailed exception message:

`The remote server returned an error: (500) InternalServerError. Reason: 50002: Provider Internal Error..TrackingId:427adaf8-eb0a-4a8a-af86-dc5998cc4388,TimeStamp:2019-10-09T13:04:58.7861049Z`

Any help would be greatly appriciated

**Comment by marstr** [comment]
Howdy, we've confirmed with your TrackingId that you were impacted by a service incident over the last 18 hours or so. It has since been mitigated, but please feel free to open a support request if you'd like more details.

**Comment by AlphaCreative-Mike** [comment]
@marstr - I'm having the same issue now.  It started on 12/12/2019 at 7am EST.  I have an SR open but they have been unable to find anything.  Our code in production has not changed in years.  I can reproduce this issue consistently with my existing production hub and new hubs that I create to troubleshoot, but not my test hub.  Is there another service incident?

**Comment by AlphaCreative-Mike** [comment]
Apparently Azure implemented TLS changes that broke my existing code.  I'm stilling waiting to find out why this change was made because there was no announcement at the time.  Adding this line fixed my issue: System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

**Comment by hirandesai** [comment]
@marstr - Can you help me as well?
I'm seeing similar error for GetRegistrationsByTagAsync on NotificationHubClient.
`Microsoft.Azure.NotificationHubs.Messaging.MessagingException: .TrackingId:7f87bc9f-edfb-4b73-94c3-119a05e0f0bd_G14,TimeStamp:2/22/2020 4:30:01 PM at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendRequestAsync>d__126.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendRequestAsync>d__125.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.NotificationHubs.NotificationHubClient.<GetAllEntitiesImplAsync>d__117`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at`

Let me know if you need additional information.
Thank you.
