### ISSUE TITLE
the push notification system handle for the registration is invalid - iOS

### ISSUE THREAD

**Issue by neil445** [Azure/azure-notificationhubs-dotnet#98]
Hello,

I'm not quite sure, but it's been a rough day for me getting this to work since iOS 13.
I'm trying to send a test message via the Notification Hub window from the Server explorer in VS2015. I'm getting this "the push notification system handle for the registration is invalid" error.

I followed the guide and here's what I got. 

![image](https://user-images.githubusercontent.com/18462598/67076173-344cb280-f1bf-11e9-9d39-13961af986c8.png)

I'll try to run through the guide again. I got it working before all the shebang from iOS13.

thanks

**Comment by neil445** [comment]
odd, it now works. 

since iOS 13, the device token doesn't need trimming of '<' and '>' characters.
So I removed that line of code, and left the line of code that trims spaces and transforms the device token string to uppercase.

I just removed the line also and it now works.
Not sure if that's the cause, seems a bit weird.

I might close this issue soon if everything works fine.

**Comment by marstr** [comment]
Howdy @neil445, sorry you're still running into trouble. I'm going to close this issue out for now, because I don't see any actionable items yet. If you get to the bottom of your issues, and there's something we can help with, feel free to ping us here or open a new issue.

**Comment by brannon** [comment]
@neil445 are you using our iOS SDK? If so, our most recent version (2.0.4) fixes this issue.

If not, then you are correct that a change in iOS 13 changed the way `NSData` objects are formatted when using the `description` function. This was a common way for people to format the token as a string.

As lots of people have pointed out though, `description` is more for debugging purposes and not intended to be used to format objects as specific strings.

If you are interested, here is the helper function we wrote in the iOS SDK to properly convert the `NSData` token to a string:
https://github.com/Azure/azure-notificationhubs-ios/blob/master/src/WindowsAzureMessaging/WindowsAzureMessaging/SBNotificationHub.m#L80

Hope that helps!

**Comment by Waaheeda** [comment]
@brannon the link u share is not working, saying page not found @neil445 could you please share your solution here

**Comment by nyluntu** [comment]
Working link: https://github.com/Azure/azure-notificationhubs-ios/blob/09df89f4230e2d0d98bb464e72611be2f9c90e4a/WindowsAzureMessaging/WindowsAzureMessaging/SBNotificationHub.m#L80

**Comment by vijaypratap845** [comment]
I am facing the same issue. I do not get push in some specific devices and I got the same exception. Please help

**Comment by brannon** [comment]
Hi @vijaypratap845 , if you are getting this exception then it's possible you are using an older version of the Notification Hubs SDK. You should upgrade to version 2.0.4 or newer.

If that doesn't solve the problem, please open a new issue in this repository so someone can take a look. The team usually won't see comments on closed issues.

**Comment by pedromramalho** [comment]
Can some one help I have the same problem IOS14, and when i try the test in Azure Portal I get 
apple | 6321218213637372908-5225854469778412245-3 | The Push Notification System handle for the registration is invalid
with this basic payload {"aps":{"alert":"Notification Hub test notification"}}, and the registration is removed from the hub

**Comment by jevinruv** [comment]
> Can some one help I have the same problem IOS14, and when i try the test in Azure Portal I get apple | 6321218213637372908-5225854469778412245-3 | The Push Notification System handle for the registration is invalid with this basic payload {"aps":{"alert":"Notification Hub test notification"}}, and the registration is removed from the hub

May be you already resolved it, just adding what I did (after many hours of researching) Assuming you have everything in place.
Probably in ANH you have set it as "Production", change it to "Sandbox" when you development via Xcode, after development change is back to Production.
